version: '3'

services:
  container_name: express-prod
  build:
    context: .
    dockerfile: Dockerfile-prod
  volumes:
    - './express-backend:/express-backend'
    - '/express-backend/node_modules'
  environment:
    - NODE_ENV=production
  ports:
    - 5000:5000
    - 9229:9229
  command: npm start