version: '3.7'

services:
  react-frontend:
    container_name: react-dev
    build:
      context: ./services/react-frontend
      dockerfile: Dockerfile
    volumes:
     - './services/react-frontend:/react-frontend'
     - '/react-frontend/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

  express-backend:
    container_name: express-dev
    image: express-backend
    build:
      context: ./services/express-backend
      dockerfile: Dockerfile
    volumes:
      - './services/express-backend:/express-backend'
      - '/express-backend/node_modules'
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true

