version: '3.7'

services:
  react-prod:
    container_name: react-prod
    build:
      context: ./services/react-frontend
      dockerfile: Dockerfile-prod
    volumes:
     - './services/react-frontend:/react-frontend'
     - '/react-frontend/node_modules'
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production

  express-backend:
    container_name: express-prod
    build:
      context: ./services/express-backend
      dockerfile: Dockerfile-prod
    volumes:
      - './services/express-backend:/express-backend'
      - '/express-backend/node_modules'
    ports:
      - 5000:5000
      - 9229:9229
    environment:
      - NODE_ENV=development
    command: npm start

networks:
  backend:
    driver: bridge